FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5009

CMD ["gunicorn", "--bind", "0.0.0.0:5009", "--workers", "2", "--timeout", "600", "app:app"]
